name: Keycloak deployment
on:
  workflow_dispatch:
    inputs:
      environment:
        description: Environment
        required: true
        default: dev | staging | prod

jobs:
  deployment:
    runs-on: ubuntu-latest
    name: Helm install Keycloak
    environment: ${{ inputs.environment }}
    steps:
      - run: echo "Job was triggered by ${{ github.event_name }}, branch ${{ github.ref }}, running on ${{ runner.os }}."
      - name: Check out repository code
        uses: actions/checkout@v2

      - uses: danielr1996/envsubst-action@1.0.0
        env:
          HOSTNAME: ${{ secrets.HOSTNAME }}
          host: "$host"
        with:
          input: statefulset/ingress_tmpl.yml
          output: statefulset/ingress.yml

      - name: Create namespace
        uses: actions-hub/kubectl@master
        continue-on-error: true
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: create namespace ${{ secrets.NAMESPACE }}

      - name: Deploy Keycloak to cluster
        uses: wahyd4/kubectl-helm-action@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG }}
        with:
          args: |
            helm repo add codecentric https://codecentric.github.io/helm-charts
            helm repo update
            helm upgrade keycloak codecentric/keycloak --install -f statefulset/values.yaml -n ${{ secrets.NAMESPACE }} \
              --set image.tag=${{ secrets.VERSION }},extensions.version=${{ secrets.KC_EXT_VERSION }} \
              --set autoscaling.minReplicas=${{ secrets.KC_MIN_PODS }},autoscaling.maxReplicas=${{ secrets.KC_MAX_PODS }} \
              --set db.name=${{ secrets.KC_DB_NAME }},db.address=${{ secrets.KC_DB_ADDRESS }},db.user=${{ secrets.KC_DB_USER }},db.password=${{ secrets.KC_DB_PASSWORD }} \
              --set admin.user=${{ secrets.KC_USER }},admin.password=${{ secrets.KC_USER_PASSWORD }} \
              --set nexus.user=${{ secrets.NEXUS_THEME_USER }},nexus.password=${{ secrets.NEXUS_THEME_PASSWORD }}

      - name: Create Ingress resource
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: apply -f statefulset/ingress.yml -n ${{ secrets.NAMESPACE }}

      - run: echo "This job's status is ${{ job.status }}."
